2020-07-20 12:34:20,790 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 12:34:20,790 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 12:34:20,790 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 12:44:08,209 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 12:44:08,209 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 12:44:08,209 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 12:44:27,771 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 12:44:27,772 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 12:44:27,772 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 12:44:37,409 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 12:44:37,409 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 12:44:37,409 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 12:44:37,754 - test_login - INFO - 准备测试前置 - [test_login.py:28 ]
2020-07-20 12:44:37,763 - test_login - INFO - 开始测试：登录成功 - [test_login.py:33 ]
2020-07-20 12:44:38,100 - test_login - INFO - 结束测试：登录成功 - [test_login.py:42 ]
2020-07-20 12:44:38,100 - test_login - INFO - 开始测试：密码为空，登录失败 - [test_login.py:33 ]
2020-07-20 12:44:38,189 - test_login - INFO - 结束测试：密码为空，登录失败 - [test_login.py:42 ]
2020-07-20 12:44:38,191 - test_login - INFO - 开始测试：手机号码为空，登录失败 - [test_login.py:33 ]
2020-07-20 12:44:38,286 - test_login - INFO - 结束测试：手机号码为空，登录失败 - [test_login.py:42 ]
2020-07-20 12:44:38,287 - test_login - INFO - 开始测试：输入错误的密码，登录失败 - [test_login.py:33 ]
2020-07-20 12:44:38,572 - test_login - INFO - 结束测试：输入错误的密码，登录失败 - [test_login.py:42 ]
2020-07-20 12:44:38,572 - test_login - INFO - 测试后置处理 - [test_login.py:46 ]
2020-07-20 23:13:33,131 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:13:33,131 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:13:33,131 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:15:28,570 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:15:28,570 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:15:28,570 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:18:54,465 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:18:54,465 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:18:54,465 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:19:13,216 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:19:13,216 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:19:13,216 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:19:13,539 - API_20200720.testcases.test_login - INFO - 准备测试前置 - [test_login.py:28 ]
2020-07-20 23:24:45,045 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:24:45,045 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:24:45,045 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:24:45,340 - API_20200720.testcases.test_login - INFO - 准备测试前置 - [test_login.py:28 ]
2020-07-20 23:24:45,341 - API_20200720.testcases.test_login - INFO - 开始测试：登录成功 - [test_login.py:33 ]
2020-07-20 23:24:45,696 - API_20200720.testcases.test_login - INFO - 结束测试：登录成功 - [test_login.py:42 ]
2020-07-20 23:24:45,697 - API_20200720.testcases.test_login - INFO - 开始测试：密码为空，登录失败 - [test_login.py:33 ]
2020-07-20 23:24:45,777 - API_20200720.testcases.test_login - INFO - 结束测试：密码为空，登录失败 - [test_login.py:42 ]
2020-07-20 23:24:45,778 - API_20200720.testcases.test_login - INFO - 开始测试：手机号码为空，登录失败 - [test_login.py:33 ]
2020-07-20 23:24:45,853 - API_20200720.testcases.test_login - INFO - 结束测试：手机号码为空，登录失败 - [test_login.py:42 ]
2020-07-20 23:24:45,853 - API_20200720.testcases.test_login - INFO - 开始测试：输入错误的密码，登录失败 - [test_login.py:33 ]
2020-07-20 23:24:46,105 - API_20200720.testcases.test_login - INFO - 结束测试：输入错误的密码，登录失败 - [test_login.py:42 ]
2020-07-20 23:24:46,105 - API_20200720.testcases.test_login - INFO - 测试后置处理 - [test_login.py:46 ]
2020-07-20 23:35:00,470 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:35:00,471 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:35:00,471 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:37:45,221 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:37:45,221 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:37:45,221 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:40:59,103 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:40:59,104 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:40:59,104 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:41:26,114 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:41:26,115 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:41:26,115 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:41:26,449 - API_20200720.testcases.test_login - INFO - 准备测试前置 - [test_login.py:28 ]
2020-07-20 23:41:26,449 - API_20200720.testcases.test_login - INFO - 开始测试：登录成功 - [test_login.py:33 ]
2020-07-20 23:41:26,755 - API_20200720.testcases.test_login - INFO - 结束测试：登录成功 - [test_login.py:42 ]
2020-07-20 23:41:26,755 - API_20200720.testcases.test_login - INFO - 开始测试：密码为空，登录失败 - [test_login.py:33 ]
2020-07-20 23:41:26,817 - API_20200720.testcases.test_login - INFO - 结束测试：密码为空，登录失败 - [test_login.py:42 ]
2020-07-20 23:41:26,817 - API_20200720.testcases.test_login - INFO - 开始测试：手机号码为空，登录失败 - [test_login.py:33 ]
2020-07-20 23:41:26,898 - API_20200720.testcases.test_login - INFO - 结束测试：手机号码为空，登录失败 - [test_login.py:42 ]
2020-07-20 23:41:26,898 - API_20200720.testcases.test_login - INFO - 开始测试：输入错误的密码，登录失败 - [test_login.py:33 ]
2020-07-20 23:41:27,152 - API_20200720.testcases.test_login - INFO - 结束测试：输入错误的密码，登录失败 - [test_login.py:42 ]
2020-07-20 23:41:27,152 - API_20200720.testcases.test_login - INFO - 测试后置处理 - [test_login.py:46 ]
2020-07-20 23:42:01,681 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:42:01,681 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:42:01,681 - case - INFO - 测试结束 - [logger.py:44 ]
2020-07-20 23:42:02,010 - API_20200720.testcases.test_login - INFO - 准备测试前置 - [test_login.py:28 ]
2020-07-20 23:42:02,010 - API_20200720.testcases.test_login - INFO - 开始测试：登录成功 - [test_login.py:33 ]
2020-07-20 23:42:02,479 - API_20200720.testcases.test_login - INFO - 结束测试：登录成功 - [test_login.py:42 ]
2020-07-20 23:42:02,480 - API_20200720.testcases.test_login - INFO - 开始测试：密码为空，登录失败 - [test_login.py:33 ]
2020-07-20 23:42:02,540 - API_20200720.testcases.test_login - INFO - 结束测试：密码为空，登录失败 - [test_login.py:42 ]
2020-07-20 23:42:02,540 - API_20200720.testcases.test_login - INFO - 开始测试：手机号码为空，登录失败 - [test_login.py:33 ]
2020-07-20 23:42:02,603 - API_20200720.testcases.test_login - INFO - 结束测试：手机号码为空，登录失败 - [test_login.py:42 ]
2020-07-20 23:42:02,604 - API_20200720.testcases.test_login - INFO - 开始测试：输入错误的密码，登录失败 - [test_login.py:33 ]
2020-07-20 23:42:02,855 - API_20200720.testcases.test_login - INFO - 结束测试：输入错误的密码，登录失败 - [test_login.py:42 ]
2020-07-20 23:42:02,856 - API_20200720.testcases.test_login - INFO - 测试后置处理 - [test_login.py:46 ]
2020-07-20 23:42:26,226 - case - INFO - 测试开始 - [logger.py:41 ]
2020-07-20 23:42:26,226 - case - ERROR - 测试报错 - [logger.py:42 ]
2020-07-20 23:42:26,226 - case - INFO - 测试结束 - [logger.py:44 ]
